# Setup
title:               Michele Marolla
tagline:             R&D Robotics Engineer
description:         'As a robotics engineer, I try to live in a closed-loop fashion: make an error, acknowledge it, and act to improve.'
url:                 ''
baseurl:             'micmarolla.github.io'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Michele Marolla
  url:               https://www.linkedin.com/in/michele-marolla-79029829
  email:             mic.marolla@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
